import { SiteContent } from "@/content/types";

export const content: SiteContent = {
  profile: {
    name: "Nishith Sura",
    headline: "Software Engineer · AI/ML",
    phone: "774-288-0681",
    email: "nishsura@outlook.com",
    location: "Westborough, MA",
    links: {
      linkedin: "https://www.linkedin.com/in/nishsura/",
      github: "https://github.com/nishsura",
      website: "",
    },
  },
  education: {
    school: "University of Maryland, College Park",
    degree: "B.S. Computer Science (Honors)",
    focus: "Machine Learning",
    gpa: "3.8 GPA",
    graduation: "May 2026",
    location: "College Park, MD",
    courses: [
      "Artificial Intelligence",
      "Human-Computer Interaction",
      "Computer Systems",
      "Algorithms",
      "Discrete Structures",
      "Data Science",
      "Web Development",
      "Physics I & II",
      "Linear Algebra",
      "Calculus I & II",
      "Intro to MATLAB",
    ],
  },
  experience: [
    {
      company: "Amazon Web Services (AWS)",
      role: "Software Engineering Intern",
      start: "June 2025",
      end: "Aug. 2025",
      location: "Arlington, VA",
      bullets: [
        "Products & Solutions Engineering team — building a cloud-based clinical trial platform for pharma enterprises, leveraging Amazon Bedrock for AI-driven anomaly detection and insights on trial data.",
      ],
    },
    {
      company: "University of Maryland",
      role: "Undergraduate Student Researcher",
      start: "Aug. 2024",
      end: "Dec. 2024",
      location: "College Park, MD",
      bullets: [
        "Researched LLM qualitative coding performance (GPT-4o, Claude 3 Opus) using a custom codebook under Dr. Dave Levin and Julio Poveda.",
        "Measured accuracy, precision, and F1 on customer reviews; compared model performance.",
        "Co-authored a conference-style report and presented to 75+ attendees.",
      ],
    },
  ],
  projects: [
    {
      title: "stockski",
      slug: "stockski",
      stack: ["Python", "AI/ML", "Streamlit", "Prophet", "Random Forest", "REST APIs", "NLP"],
      summary: "Stock prediction app combining multiple ML techniques with real-time data and sentiment analysis.",
      bullets: [
        "Built time-series prediction with Prophet, Random Forest, Gradient Boosting, and SVR.",
        "Streamlit UI for 1,000+ stocks with indicators (RSI, MACD, Bollinger, ADX, ATR).",
        "Applied VADER sentiment; tuned models to reach ~87% predictive accuracy and reduced MAE by 23%.",
      ],
      links: { demo: "https://stockski.streamlit.app" },
    },
    {
      title: "ScreenApp",
      slug: "screenapp",
      stack: ["JavaScript", "React", "Node.js", "Express", "Socket.io", "MongoDB", "AWS", "Vercel"],
      summary: "Real-time collaboration with HD screen sharing, video streaming, and live chat.",
      bullets: [
        "React front-end with Node/Express back-end; Socket.io for real-time messaging.",
        "MongoDB for users/rooms; deployed back-end on AWS EC2 and front-end on Vercel.",
        "Served 400+ unique visitors and 100+ rooms created.",
      ],
      links: { demo: "https://screenster.vercel.app" },
    },
    {
      title: "Fantasy Football Manager",
      slug: "fantasy-football-manager",
      stack: ["Node.js", "Express", "MongoDB", "PostgreSQL", "REST API", "EJS", "Axios"],
      summary: "Fantasy football team manager with live NFL data and standings.",
      bullets: [
        "Integrated SportsDataIO API and Axios for real-time scores and standings.",
        "Dynamic EJS pages for player stats and game scores; tabulated regular season standings.",
        "Stored user-selected players and data in MongoDB and PostgreSQL with validation.",
      ],
      links: { demo: "https://fantasy-app-j8k7.onrender.com/" },
    },
  ],
  awards: [
    {
      title: "Academic Excellence Award (Nominee)",
      org: "University of Maryland",
      summary: "OMSE Academy of Academic Excellence nominee for '23, '24, '25.",
    },
    {
      title: "Dean's List Honors",
      org: "University of Maryland",
      summary: "Awarded every semester at UMD.",
    },
  ],
  skills: {
    languages: [
      "Java",
      "Python",
      "C",
      "Assembly",
      "OCaml",
      "Rust",
      "TypeScript",
      "JavaScript",
      "PHP",
      "HTML/CSS",
    ],
    tools: [
      "Git",
      "AWS",
      "Docker",
      "React",
      "Node.js",
      "Express",
      "SQL",
      "MongoDB",
      "REST APIs",
      "JavaFX",
      "JUnit",
      "MATLAB",
      "scikit-learn",
      "pandas",
      "NumPy",
    ],
  },
};
